pm = ${PM_MODE:-dynamic}

pm.max_children = ${PM_MAX_CHILDREN:-10}
pm.start_servers = ${PM_START_SERVERS:-2}
pm.min_spare_servers = ${PM_MIN_SPARE_SERVERS:-1}
pm.max_spare_servers = ${PM_MAX_SPARE_SERVERS:-3}

pm.max_requests = ${PM_MAX_REQUESTS:-0}

catch_workers_output = ${PM_CATCH_WORKERS_OUTPUT:-yes}
