pm = ${PM_MODE:-dynamic}

pm.max_children = ${PM_MAX_CHILDREN:-20}
pm.start_servers = ${PM_START_SERVERS:-4}
pm.min_spare_servers = ${PM_MIN_SPARE_SERVERS:-2}
pm.max_spare_servers = ${PM_MAX_SPARE_SERVERS:-6}

pm.max_requests = ${PM_MAX_REQUESTS:-500}

catch_workers_output = ${PM_CATCH_WORKERS_OUTPUT:-no}
