memory_limit = ${MEMORY_LIMIT}
upload_max_filesize = ${UPLOAD_MAX_FILESIZE}
max_file_uploads = ${MAX_FILE_UPLOADS}
post_max_size = ${POST_MAX_SIZE}

realpath_cache_size=${REALPATH_CACHE_SIZE}
realpath_cache_ttl=${REALPATH_CACHE_TTL}
error_log=${ERROR_LOG}
date.timezone=${DATE_TIMEZONE}

; https://github.com/phpredis/phpredis
session.save_handler=${SESSION_SAVE_HANDLER}
session.save_path=${SESSION_SAVE_PATH}

