memory_limit = ${MEMORY_LIMIT:-256M}

upload_max_filesize = ${UPLOAD_MAX_FILESIZE:-20M}
post_max_size = ${POST_MAX_SIZE:-20M}
max_file_uploads = ${MAX_FILE_UPLOADS:-20}

realpath_cache_size = ${REALPATH_CACHE_SIZE:-4096K}
realpath_cache_ttl = ${REALPATH_CACHE_TTL:-600}

error_log = ${ERROR_LOG:-/proc/self/fd/2}

date.timezone = ${DATE_TIMEZONE:-UTC}

; https://github.com/phpredis/phpredis
session.save_handler = ${SESSION_SAVE_HANDLER:-files}
session.save_path = ${SESSION_SAVE_PATH:-/tmp}